// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bujzuxksiisvtwmnrhfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1anp1eGtzaWlzdnR3bW5yaGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTE2MTMsImV4cCI6MjA2MzY4NzYxM30.UU2qfmUZhTDkeaB7Ez8HKGC5QVKKDbTiGcCyFbJdITU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);